/*
 * GaborNeuroFit - Core Domain Types & Clinical Interfaces
 * Copyright (C) 2026 Pavel Korotkov
 *
 * This file serves as the Single Source of Truth (SSoT) for all data structures.
 * Modifying this file establishes the fundamental rules for the TypeScript compiler
 * validating the integration of visual presentation, persistent data, and state management.
 */

// ============================================================================
// 1. DOMAIN PRIMITIVES (Strict Type Literals)
// ============================================================================

export type AppMode = 'gabor' | 'synoptophore' | 'rds';
export type EyeSide = 'left' | 'right';
export type GaborPreset = 'occlusion' | 'blitz' | 'binocular' | 'flicker' | 'peripheral' | 'custom';
export type FlashDurationMode = 'adaptive' | '100' | '180' | '200' | '350';
export type CrowdingMode = 'vertical' | 'horizontal' | 'all';
export type SynopState = 'idle' | 'align' | 'pulling';
export type SynopTargetType = 'ring-dot' | 'cross-square';
export type RdsFloatSpeed = 'slow' | 'medium' | 'fast';
export type Language = 'en' | 'ru';

// ============================================================================
// 2. APPLICATION GLOBAL STATE (Store)
// ============================================================================

export interface AppState {

    // --- System & Meta ---
    sessionId: string;
    currentLang: Language;
    appMode: AppMode;
    isPaused: boolean;
    isMuted: boolean;

    // --- Global Hardware & Dichoptic Calibration ---

    /**
     * @description Is 3D color-channel splitting enabled (Red/Cyan calibration).
     *
     * @clinical Transitioning from patching (occlusion) to dichoptic viewing. The
     * visual cortex (V1/V2) receives independent signals simultaneously natively simulating
     * binocular integration, bypassing physical physical eye covers to break interocular suppression.
     */
    isAnaglyphEnabled: boolean;
    redEyeSide: EyeSide;
    lazyEyeSide: EyeSide;

    /**
     * @description Contrast attenuation multiplexer for the dominant eye [0.1 to 1.0].
     *
     * @clinical Contrast Balancer. The dominant eye naturally suppresses the lazy eye.
     * By programmatically reducing the dominant eye's contrast mapping (e.g. down to 20%),
     * we artificially equalize signal strength in the cortex, forcing the brain to unblock
     * the weak eye's neural pathway to integrate the combined image.
     */
    strongEyeContrastFactor: number;
    calibratorLeftR: number;
    calibratorRightG: number;
    calibratorRightB: number;

    // --- Gabor Perceptual Learning Modality ---

    presetMode: GaborPreset;
    lastGaborPreset: GaborPreset;

    /**
     * @description Active difficulty stage (1 to 5).
     *
     * @clinical Represents spatial frequency (cycles per degree). Higher levels encode
     * denser, thinner Gabor lines correlating to higher visual acuity demands.
     * This pushes V1 neural networks to map smaller receptive visual fields.
     */
    currentLevel: number;

    /**
     * @description Adaptive contrast threshold generated by the staircase algorithm.
     *
     * @clinical Driving neuroplasticity requires testing visually at the absolute threshold
     * of detection. Rendering targets slightly below comfortable perceptibility triggers
     * Hebbian synaptic remodeling to boost cortical sensitivity across the weak optic nerve.
     */
    autoContrast: number;

    score: number;
    total: number;
    correctStreak: number;
    staircaseStreak: number;

    /**
     * @description Limits visual stimulus exposure duration.
     *
     * @clinical Saccadic eye movements require ~200ms to plan and execute. Flashes
     * faster than 200ms physically prevent the patient from darting their eye to 'cheat'
     * by looking at the target with a non-suppressed peripheral retinal point.
     */
    flashDurationMode: FlashDurationMode;
    autoAdvance: boolean;
    allowStageAdvance: boolean;

    /**
     * @description Toggles orthogonal lines surrounding the main foveal target.
     *
     * @clinical Lateral Visual Crowding. Amblyopic eyes suffer from severe spatial
     * crowding where adjacent details blur together. Flankers push lateral inhibition
     * networks to filter visual noise and lock onto central features.
     */
    isCrowdingEnabled: boolean;
    crowdingMode: CrowdingMode;
    flankerDistanceCoeff: number;

    isOrthogonalFlankersEnabled: boolean;
    isDynamicFlankersEnabled: boolean;

    /**
     * @description Moves the Gabor patch randomly away from the center cross.
     *
     * @clinical Re-establishes parafoveal awareness and spatial localization tracking
     * that degrades during prolonged central fixation exercises.
     */
    isPeripheralEnabled: boolean;
    allowLowContrast: boolean;
    allowWideVariance: boolean;
    allowShapeVariance: boolean;
    isStaticEnabled: boolean;

    /**
     * @description Toggles 10 Hz Alpha-Resonance stroboscopic pulsing of the stimulus.
     *
     * @clinical Generates Steady-State Visually Evoked Potentials (SSVEP). 10Hz resonance
     * forcibly bypasses cortical top-down inhibition and completely eliminates Troxler's fading
     * adaptation across low-contrast stimuli.
     */
    isFlickerEnabled: boolean;
    isFusionLockEnabled: boolean;
    isPermanentCrossEnabled: boolean;

    // --- Synoptophore (Vergence/Strabismus) Modality ---

    synopState: SynopState;

    /**
     * @description Current horizontal target offset from geometric center.
     *
     * @clinical Tracks the current horizontal strabismic deviation angle
     * (esotropia / exotropia). Mathematically correlates to Prism Diopters (Δ)
     * measuring the physical extent of extraocular muscle misalignment.
     */
    synopTargetX: number;
    synopTargetY: number;
    synopStartDistance: number;

    /**
     * @description The interval (ms) representing the smooth motor pulling rate.
     *
     * @clinical Dictates motor vergence strain intensity. Pulling targets too fast
     * breaks ocular sensor-fusion locks. Optimal slower speeds progressively encourage
     * the extraocular muscles to adapt and maintain optical structural binocularity.
     */
    synopPullSpeed: number;
    synopTargetType: SynopTargetType;
    synopShowLazyGrid: boolean;
    synopShowStrongGrid: boolean;
    synopTargetSize: number;
    synopScore: number;
    synopFlickerActive: boolean;
    synopLockVertical: boolean;
    synopLockHorizontal: boolean;
    synopStrongEyeContrastFactor: number;
    synopCalibratorLeftR: number;
    synopCalibratorRightG: number;
    synopCalibratorRightB: number;

    // --- Random Dot Stereogram (RDS) Modality ---

    rdsLevel: number;

    /**
     * @description Visual size of a single noise generator cell in pixels.
     *
     * @clinical Smaller dots (2px) yield a denser stereoscopic correlation matrix.
     * Reducing macro-contrast facilitates substantially cleaner 3D binocular disparity
     * computation in V2 visual layers without introducing ghosting elements.
     */
    rdsDotSize: number;
    rdsDensity: number;
    rdsStartDisparity: number;

    /**
     * @description Subpixel horizontal shift disparity mapped between the two eye channels.
     *
     * @clinical Binocular Disparity shift. Small shifts (1-2px) construct extreme micro-stereopsis.
     * Fusing a 1-pixel shift clinically demonstrates excellent stereoscopic recovery of depth
     * perception up to ~20 arcseconds of stereoscopic resolution.
     */
    rdsDisparity: number;
    rdsAutoAdvance: boolean;
    rdsTargetSide: EyeSide;
    rdsScore: number;
    rdsTotal: number;
    rdsStreak: number;
    rdsStaircaseStreak: number;
    rdsIsDynamic: boolean;
    rdsRandomizeVertical: boolean;
    rdsTargetY: number;
    rdsIsFloating: boolean;
    rdsFloatSpeed: RdsFloatSpeed;
    rdsIsPermanentCrossEnabled: boolean;
    rdsDriftX: number;
    rdsDriftY: number;

    // --- Session Constraints & Timers ---
    sessionLimit: number;
    rdsSessionLimit: number;
    timerLimitMinutes: number;
    timerRemainingSeconds: number;
    timerIsRunning: boolean;
    savedTimerRunningState: boolean;

    // --- Non-persistent Runtime Vectors ---
    isWaitingForAnswer: boolean;
    trialHistory: number[];
    rdsHistory: number[];
}

// ============================================================================
// 3. DATABASE REPOSITORY MODELS (Relational Entities)
// ============================================================================

export interface SessionCore {
    /** @description Unique session identifier, format UUID_Date */
    id: string;
    /** @description Foreign key linking to the active patient profile UID */
    userId: string;
    /** @description Unix timestamp recorded at session initiation */
    timestamp: number;
    /** @description The specific clinical protocol algorithm used during the block */
    protocol: GaborPreset | 'synoptophore' | 'rds';
}

export interface GaborSession extends SessionCore {
    score: number;
    total: number;
    level: number;
    contrast: number;
    speed: FlashDurationMode;
    isAnaglyph: boolean;
    balance: number;
    lazyEyeSide: EyeSide;
    isFlickerEnabled: boolean;
    isCrowdingEnabled: boolean;
    isPeripheralEnabled: boolean;
    isPermanentCrossEnabled: boolean;
    flankerDistanceCoeff: number;
}

export interface SynoptophoreSession extends SessionCore {
    synopTargetX: number;
    synopTargetY: number;
    synopStartDistance: number;
    synopOutcome: 'success' | 'slip';
    speed: number;
    isAnaglyph: boolean;
    balance: number;
    lazyEyeSide: EyeSide;
    synopFlickerActive: boolean;
}

export interface RdsSession extends SessionCore {
    score: number;
    total: number;
    level: number;
    isAnaglyph: boolean;
    balance: number;
    lazyEyeSide: EyeSide;
    rdsDotSize: number;
    rdsDensity: number;
    rdsDisparity: number;
}
